name: Pubobot

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

jobs:      
  docker_build:
    name: "Building aqtiongame/pubobot:${{ github.event.inputs.release_tag }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Pubobot (alpine)
        run: |
          docker build -t aqtiongame/pubobot:alpine-${{ github.event.inputs.release_tag }} -f Dockerfile .
          docker push aqtiongame/pubobot:alpine-${{ github.event.inputs.release_tag }}